_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
#  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 1
INPUT:
  MIN_SIZE_TRAIN: (270, ) #, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 270
DATASETS:
  TRAIN: ('sacrum_train','sacrum_test')
  TEST: ('sacrum_test',)
SOLVER:
  IMS_PER_BATCH: 40
  STEPS: (2000, 4000)
  MAX_ITER: 10000
  WARMUP_ITERS: 100
