_BASE_: "Base-RCNN-C4.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 16
    NUM_CLASSES: 1  # only has one class
DATALOADER:
  NUM_WORKERS: 2
INPUT:
  MIN_SIZE_TRAIN: (270, ) #, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 270
DATASETS:
  TRAIN: ('sacrum_train','sacrum_validation')
  TEST: ('sacrum_test',)
SOLVER:
  IMS_PER_BATCH: 80
  STEPS: (1000, 1500)
  MAX_ITER: 2000
  WARMUP_ITERS: 100