_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  # WEIGHTS: "detectron2://COCO-Detection/faster_rcnn_R_50_FPN_3x/137849458/model_final_280758.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 128
    NUM_CLASSES: 1  # only has one class (licenseplate)
DATALOADER:
  NUM_WORKERS: 2
INPUT:
  MIN_SIZE_TRAIN: (270, ) #, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 270
DATASETS:
  TRAIN: ('sacrum_train','sacrum_test')
  TEST: ('sacrum_test',)
SOLVER:
  IMS_PER_BATCH: 80
  STEPS: (2000, 4000)
  MAX_ITER: 1000
  WARMUP_ITERS: 100
